//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlineStoreEntities : DbContext
    {
        private static onlineStoreEntities _context;
        public onlineStoreEntities()
            : base("name=onlineStoreEntities")
        {
        }

        public static onlineStoreEntities GetContext()
        {
            if (_context == null)
            {
                _context=new onlineStoreEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<goods> goods { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<orders_details> orders_details { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
        public virtual DbSet<statuses> statuses { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
