//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_details
    {
        public int ID { get; set; }
        public int order_ID { get; set; }
        public int good_ID { get; set; }
        public int quantity { get; set; }
    
        public virtual goods goods { get; set; }
        public virtual orders orders { get; set; }
    }
}
