//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int ID { get; set; }
        public int user_ID { get; set; }
        public int good_ID { get; set; }
        public string text { get; set; }
    
        public virtual goods goods { get; set; }
        public virtual users users { get; set; }
    }
}
